# Generated by Django 5.0.4 on 2024-05-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
        ('store', '0003_product_image'),
    ]

    operations = [
    ]
